<?php

namespace ContainerZ3Z3zxI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PCjCszmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pCjCszm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pCjCszm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\HomeController::add' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\HomeController::addMember' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\HomeController::delete' => ['privates', '.service_locator.iyEwlLH', 'get_ServiceLocator_IyEwlLHService', true],
            'App\\Controller\\HomeController::deleteMember' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\HomeController::edit' => ['privates', '.service_locator.0n6uXa.', 'get_ServiceLocator_0n6uXa_Service', true],
            'App\\Controller\\HomeController::editMember' => ['privates', '.service_locator.PaJQGxZ', 'get_ServiceLocator_PaJQGxZService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\HomeController::members' => ['privates', '.service_locator.z4vVS.d', 'get_ServiceLocator_Z4vVS_DService', true],
            'App\\Controller\\HomeController::pdt' => ['privates', '.service_locator.iyEwlLH', 'get_ServiceLocator_IyEwlLHService', true],
            'App\\Controller\\HomeController::products' => ['privates', '.service_locator.z4vVS.d', 'get_ServiceLocator_Z4vVS_DService', true],
            'App\\Controller\\HomeController::user' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YT8XVZ7', 'get_ServiceLocator_YT8XVZ7Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.fV_Pg_z', 'get_ServiceLocator_FVPgZService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\HomeController:add' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\HomeController:addMember' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\HomeController:delete' => ['privates', '.service_locator.iyEwlLH', 'get_ServiceLocator_IyEwlLHService', true],
            'App\\Controller\\HomeController:deleteMember' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\HomeController:edit' => ['privates', '.service_locator.0n6uXa.', 'get_ServiceLocator_0n6uXa_Service', true],
            'App\\Controller\\HomeController:editMember' => ['privates', '.service_locator.PaJQGxZ', 'get_ServiceLocator_PaJQGxZService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\HomeController:members' => ['privates', '.service_locator.z4vVS.d', 'get_ServiceLocator_Z4vVS_DService', true],
            'App\\Controller\\HomeController:pdt' => ['privates', '.service_locator.iyEwlLH', 'get_ServiceLocator_IyEwlLHService', true],
            'App\\Controller\\HomeController:products' => ['privates', '.service_locator.z4vVS.d', 'get_ServiceLocator_Z4vVS_DService', true],
            'App\\Controller\\HomeController:user' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YT8XVZ7', 'get_ServiceLocator_YT8XVZ7Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.fV_Pg_z', 'get_ServiceLocator_FVPgZService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\HomeController::add' => '?',
            'App\\Controller\\HomeController::addMember' => '?',
            'App\\Controller\\HomeController::delete' => '?',
            'App\\Controller\\HomeController::deleteMember' => '?',
            'App\\Controller\\HomeController::edit' => '?',
            'App\\Controller\\HomeController::editMember' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\HomeController::members' => '?',
            'App\\Controller\\HomeController::pdt' => '?',
            'App\\Controller\\HomeController::products' => '?',
            'App\\Controller\\HomeController::user' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::registration' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\HomeController:add' => '?',
            'App\\Controller\\HomeController:addMember' => '?',
            'App\\Controller\\HomeController:delete' => '?',
            'App\\Controller\\HomeController:deleteMember' => '?',
            'App\\Controller\\HomeController:edit' => '?',
            'App\\Controller\\HomeController:editMember' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\HomeController:members' => '?',
            'App\\Controller\\HomeController:pdt' => '?',
            'App\\Controller\\HomeController:products' => '?',
            'App\\Controller\\HomeController:user' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:registration' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
