<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMAs7lqk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMAs7lqk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMAs7lqk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMAs7lqk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMAs7lqk\App_KernelDevDebugContainer([
    'container.build_hash' => 'MAs7lqk',
    'container.build_id' => 'dd7c20e8',
    'container.build_time' => 1611575059,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMAs7lqk');
