<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRxXvSYF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRxXvSYF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRxXvSYF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRxXvSYF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRxXvSYF\App_KernelDevDebugContainer([
    'container.build_hash' => 'RxXvSYF',
    'container.build_id' => '639ad397',
    'container.build_time' => 1611594319,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRxXvSYF');
