<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQxKV5Zs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQxKV5Zs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQxKV5Zs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQxKV5Zs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQxKV5Zs\App_KernelDevDebugContainer([
    'container.build_hash' => 'QxKV5Zs',
    'container.build_id' => 'b3bcc82d',
    'container.build_time' => 1611602765,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQxKV5Zs');
